# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 549e65dd2bbda645917b0ae80c2e0714a60e5cbb78530cafe85b0281532a9ac26dd484f2776e157e769afdb3528dab3523dbf030b9416518bb6c5d6b5344c628

test:
  secret_key_base: b14b5a23f60b50c13c793d382f813902d7b60c9d0305616730eb773e1b2899a649cb22ebc8e38e6d73d30c34bbc893af7b915f88d43d0d0c1b74d122461f3cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
